### ISSUE TITLE
i imported the project,but run" mvn install" error like this come out,can you help me 无效的标记: --release

### ISSUE THREAD

**Issue by lipingping951462** [casinthecloud/cas-overlay-demo#21]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cas-overlay-demo: Fatal error compiling: 无效的标记: --release ->
 [Help 1]

**Comment by leleuj** [comment]
Are you sure you use the right JDK? It must be at least JDK 11.
