### ISSUE TITLE
Manifest not found

### ISSUE THREAD

**Issue by AlejandroPerezAnuncibay** [casinthecloud/cas-overlay-demo#23]
Hey, I was trying to set up your cas server and I always get this error following your instructions, any idea?
`/usr/lib/jvm/java-11-openjdk-11.0.14.0.9-2.el8_5.x86_64/bin/java -jar target/cas.war
no hay ningún atributo de manifiesto principal en target/cas.war
`

Thanks

**Comment by leleuj** [comment]
This demo must be run as a WAR in a Tomcat (`cas-server-webapp` dependency) not as an executable JAR.
